packages:
  - packages/*
  - apps/*
  - lib/*
catalog:
  js-yaml: ^4.1.0
  turbo: 2.5.6
  typescript: 5.9.2
  vite: 7.1.4
  vitest: ^3.2.4
  '@ast-grep/napi': ^0.39.4
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.6
  '@changesets/git': ^3.0.4
  '@clack/prompts': ^0.11.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@ctrl/tinycolor': ^4.1.0
  '@eslint/js': ^9.34.0
  '@faker-js/faker': ^10.0.0
  '@iconify/json': ^2.2.381
  '@iconify/tailwind': ^1.2.0
  '@iconify/vue': ^5.0.0
  '@intlify/core-base': ^11.1.12
  '@intlify/unplugin-vue-i18n': ^11.0.0
  '@jspm/generator': ^2.6.4
  '@manypkg/get-packages': ^3.1.0
  '@nolebase/vitepress-plugin-git-changelog': ^2.18.2
  '@playwright/test': ^1.55.0
  '@pnpm/workspace.read-manifest': ^1000.2.2
  '@stylistic/stylelint-plugin': ^4.0.0
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/vue-query': ^5.86.0
  '@tanstack/vue-store': ^0.7.4
  '@types/archiver': ^6.0.3
  '@types/eslint': ^9.6.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/json-bigint': ^1.0.4
  '@types/jsonwebtoken': ^9.0.10
  '@types/lodash.clonedeep': ^4.5.9
  '@types/lodash.get': ^4.4.9
  '@types/lodash.isequal': ^4.5.8
  '@types/lodash.set': ^4.3.9
  '@types/node': ^24.3.1
  '@types/nprogress': ^0.2.3
  '@types/postcss-import': ^14.0.3
  '@types/qrcode': ^1.5.5
  '@types/qs': ^6.14.0
  '@types/sortablejs': ^1.15.8
  '@typescript-eslint/eslint-plugin': ^8.42.0
  '@typescript-eslint/parser': ^8.42.0
  '@vee-validate/zod': ^4.15.1
  '@vite-pwa/vitepress': ^1.0.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/reactivity': ^3.5.21
  '@vue/shared': ^3.5.21
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.9.0
  '@vueuse/integrations': ^13.9.0
  '@vueuse/motion': ^3.0.3
  ant-design-vue: ^4.2.6
  archiver: ^7.0.1
  autoprefixer: ^10.4.21
  axios: ^1.11.0
  axios-mock-adapter: ^2.1.0
  cac: ^6.7.14
  chalk: ^5.6.0
  cheerio: ^1.1.2
  circular-dependency-scanner: ^2.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.0.2
  consola: ^3.4.2
  cross-env: ^10.0.0
  cspell: ^9.2.1
  cssnano: ^7.1.1
  cz-git: ^1.12.0
  czg: ^1.12.0
  dayjs: ^1.11.18
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^17.2.2
  echarts: ^6.0.0
  element-plus: ^2.11.1
  eslint: ^9.34.0
  eslint-config-turbo: ^2.5.6
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^54.3.1
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.21.3
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^60.0.0
  eslint-plugin-unused-imports: ^4.2.0
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.4.0
  execa: ^9.6.0
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^16.3.0
  h3: ^1.15.4
  happy-dom: ^18.0.1
  html-minifier-terser: ^7.2.0
  is-ci: ^4.1.0
  json-bigint: ^1.0.0
  jsonc-eslint-parser: ^2.4.0
  jsonwebtoken: ^9.0.2
  lefthook: ^1.12.3
  lodash.clonedeep: ^4.5.0
  lodash.get: ^4.4.2
  lodash.isequal: ^4.5.0
  lodash.set: ^4.3.2
  lucide-vue-next: ^0.542.0
  medium-zoom: ^1.1.0
  naive-ui: ^2.42.0
  nitropack: ^2.12.5
  nprogress: ^0.2.0
  ora: ^8.2.0
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.5.0
  pkg-types: ^2.3.0
  playwright: ^1.55.0
  postcss: ^8.5.6
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.0
  postcss-import: ^16.1.1
  postcss-preset-env: ^10.3.1
  postcss-scss: ^4.0.9
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  publint: ^0.3.12
  qrcode: ^1.5.4
  qs: ^6.14.0
  radix-vue: ^1.9.17
  resolve.exports: ^2.0.3
  rimraf: ^6.0.1
  rollup: ^4.50.0
  rollup-plugin-visualizer: ^6.0.3
  sass: ^1.92.0
  secure-ls: ^2.0.0
  sortablejs: ^1.15.6
  stylelint: ^16.23.1
  stylelint-config-recess-order: ^7.2.0
  stylelint-config-recommended: ^17.0.0
  stylelint-config-recommended-scss: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^39.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.12.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tailwindcss-animate: ^1.0.7
  theme-colors: ^0.1.0
  tippy.js: ^6.3.7
  unbuild: ^3.6.1
  unplugin-element-plus: ^0.10.0
  vee-validate: ^4.15.1
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^1.0.3
  vite-plugin-vue-devtools: ^8.0.1
  vitepress: ^1.6.4
  vitepress-plugin-group-icons: ^1.6.3
  vue: ^3.5.21
  vue-eslint-parser: ^10.2.0
  vue-i18n: ^11.1.12
  vue-json-viewer: ^2.2.22
  vue-router: ^4.5.1
  vue-tippy: ^6.7.1
  vue-tsc: ^3.0.6
  vxe-pc-ui: ^4.9.15
  vxe-table: ^4.16.7
  watermark-js-plus: ^1.6.3
  zod: ^4.1.5
  zod-defaults: ^0.1.3
